# Generated by Django 5.2.4 on 2025-07-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galeria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='cover_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_cover', to='core.image', verbose_name='Imagem de Capa'),
        ),
    ]
