# Generated by Django 5.2.4 on 2025-07-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeria_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='watermark_file_used',
        ),
        migrations.AddField(
            model_name='galeria',
            name='watermark_choice',
            field=models.CharField(blank=True, choices=[('', "Sem Marca D'água")], help_text="Selecione uma marca d'água para aplicar nas imagens desta galeria.", max_length=100, verbose_name="Marca D'água"),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file_watermarked',
            field=models.ImageField(blank=True, null=True, upload_to='galeria_images/watermarked/', verbose_name="Com Marca D'água"),
        ),
    ]
