# Generated by Django 5.2.4 on 2025-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_galeria_watermark_file_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='watermark_choice',
            field=models.CharField(blank=True, choices=[('', "Sem Marca D'água"), ('1-logoescola-bco.png', '1 logoescola bco.png'), ('10-tv_jr-ranieri news-vd.jpg', '10 tv jr ranieri news vd.jpg'), ('2-logo_escola-pbtransp.png', '2 logo escola pbtransp.png'), ('3-sim_coz-transp.png', '3 sim coz transp.png'), ('4-simoninha_na_cozinha.png', '4 simoninha na cozinha.png'), ('5-coral.png', '5 coral.png'), ('6-coral_invert.png', '6 coral invert.png'), ('7-interclasses.png', '7 interclasses.png'), ('8-formatura_5ano.png', '8 formatura 5ano.png'), ('9-tv_jr-ranieri news-transp.png', '9 tv jr ranieri news transp.png')], help_text="Selecione uma marca d'água para aplicar nas imagens desta galeria.", max_length=100, verbose_name="Marca D'água"),
        ),
    ]
