# Generated by Django 5.2.4 on 2025-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_galeria_watermark_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_photographer',
            field=models.BooleanField(default=False, verbose_name='É Fotógrafo?'),
        ),
    ]
