# Generated by Django 5.2.4 on 2025-07-19 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Curtido Em')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.galeria', verbose_name='Galeria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Curtida de Galeria',
                'verbose_name_plural': 'Curtidas de Galerias',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'galeria')},
            },
        ),
    ]
