# Generated by Django 5.2.4 on 2025-08-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galerialike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Música')),
                ('composer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Compositor')),
                ('youtube_video_id', models.CharField(help_text="O ID (os últimos caracteres) do link do vídeo do YouTube. Ex: para 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', o ID é 'dQw4w9WgXcQ'.", max_length=20, verbose_name='ID do Vídeo do YouTube')),
                ('curiosity', models.TextField(blank=True, null=True, verbose_name='Curiosidade sobre a música')),
                ('inclusion_year', models.PositiveIntegerField(blank=True, help_text='O ano em que a música foi incluída no repertório.', null=True, verbose_name='Ano de Inclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Música do Repertório',
                'verbose_name_plural': 'Músicas do Repertório',
                'db_table': 'repertorio_coral',
                'ordering': ['title'],
            },
        ),
    ]
