# Generated by Django 5.2.4 on 2025-08-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_repertorio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repertorio',
            new_name='Repertorio_Coral',
        ),
    ]
