# Generated by Django 5.2.4 on 2025-09-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_repertorio_repertorio_coral'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repertorio_coral',
            table=None,
        ),
    ]
