# Generated by Django 5.2.4 on 2025-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_repertorio_coral_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repertorio_coral',
            table='repertorio_coral',
        ),
    ]
