# Generated by Django 5.2.4 on 2025-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_repertorio_coral_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCo_Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Receita')),
                ('youtube_video_id', models.CharField(help_text='O ID (os últimos caracteres) do link do vídeo do YouTube.', max_length=20, verbose_name='ID do Vídeo do YouTube')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Receita')),
                ('recipe', models.TextField(blank=True, null=True, verbose_name='Ingredientes e Modo de Preparo')),
                ('inclusion_date', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Receita do Simoninha',
                'verbose_name_plural': 'Receitas do Simoninha',
                'db_table': 'simco_receita',
                'ordering': ['-inclusion_date', 'title'],
            },
        ),
    ]
